-- Migration: Add detailed client information columns
ALTER TABLE clients ADD COLUMN city VARCHAR(255) NULL DEFAULT NULL AFTER address;
ALTER TABLE clients ADD COLUMN state VARCHAR(255) NULL DEFAULT NULL AFTER city;
ALTER TABLE clients ADD COLUMN pincode VARCHAR(20) NULL DEFAULT NULL AFTER state;
ALTER TABLE clients ADD COLUMN dob DATE NULL DEFAULT NULL AFTER pincode;
ALTER TABLE clients ADD COLUMN nominee VARCHAR(255) NULL DEFAULT NULL AFTER dob;
ALTER TABLE clients ADD COLUMN notes TEXT NULL DEFAULT NULL AFTER nominee;
