-- Migration: Add detailed client information columns (idempotent)
ALTER TABLE clients ADD COLUMN IF NOT EXISTS city VARCHAR(255) NULL DEFAULT NULL AFTER address;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS state VARCHAR(255) NULL DEFAULT NULL AFTER city;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS pincode VARCHAR(20) NULL DEFAULT NULL AFTER state;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS dob DATE NULL DEFAULT NULL AFTER pincode;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS nominee VARCHAR(255) NULL DEFAULT NULL AFTER dob;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS notes TEXT NULL DEFAULT NULL AFTER nominee;
