-- Migration: Add detailed client information columns
ALTER TABLE clients ADD COLUMN city VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE clients ADD COLUMN state VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE clients ADD COLUMN pincode VARCHAR(20) NULL DEFAULT NULL;
ALTER TABLE clients ADD COLUMN dob DATE NULL DEFAULT NULL;
ALTER TABLE clients ADD COLUMN nominee VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE clients ADD COLUMN notes TEXT NULL DEFAULT NULL;
